# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - manoj04

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_75c3237bd1b34c60a2ea9805dd06110a }}
        password: ${{ secrets.AzureAppService_ContainerPassword_15b5211a96634c81b357c619de5c8af4 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_75c3237bd1b34c60a2ea9805dd06110a }}/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'manoj04'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_f643560a43314b4d9c11bf2e78b2f1da }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_75c3237bd1b34c60a2ea9805dd06110a }}/appsvc/staticsite:${{ github.sha }}'